### ISSUE TITLE
`.egg-info` deprecation warning from `pip>=20.0`

### ISSUE THREAD

**Issue by hdiogenes** [kytos/kytos#1036]
Steps to reproduce:
```
$ pip install --upgrade pip
$ pip install kytos  # or kytos==2019.2
```

Warning emitted by pip:
>   DEPRECATION: kytos from [pypi/kytos-2019.2.tar.gz](https://files.pythonhosted.org/packages/71/db/0bf0de4a4565ce1aa54bd688ddb0dcb95fc7c3144c4735b87cdaa092ab40/kytos-2019.2.tar.gz#sha256=81ebe35a0f3c899f8b9748f619f6c507aaa284ac9e90c4573f42bc4e073db1cc ) did not indicate that it installed an .egg-info directory. Only `setup.py` projects generating `.egg-info` directories are supported. pip 20.2 will remove support for this functionality. A possible replacement is for maintainers: updating the `setup.py` of kytos. [...] You can find discussion regarding this at https://github.com/pypa/pip/issues/6998.

**Comment by gleybersonandrade** [comment]
Some observations:

- This merged PR is now rejecting projects that don't generate .egg-info, not more only showing warnings: https://github.com/pypa/pip/pull/8617

- This error occurs only when `wheel` isn't installed, when using `pip install --upgrade pip setuptools wheel`, installation occurs without any error.

- When I comment the class InstallMode of setup.py, and `run` method is running from `install`, the following outputs are showed:

1. if wheel is installed:

> Collecting pip
  Using cached https://files.pythonhosted.org/packages/bd/b1/56a834acdbe23b486dea16aaf4c27ed28eb292695b90d01dff96c96597de/pip-20.2.1-py2.py3-none-any.whl
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/ed/16/e9f5c5b86696da09298ea10c32d68ad8ea21f888e45b11aa9e615adda6c9/setuptools-49.2.1-py3-none-any.whl
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
  Found existing installation: setuptools 41.2.0
    Uninstalling setuptools-41.2.0:
      Successfully uninstalled setuptools-41.2.0
Successfully installed pip-20.2.1 setuptools-49.2.1 wheel-0.34.2
Processing /home/gleyberson/Dev/kytos-workspace/dev/core/kytos
Requirement already satisfied: appnope==0.1.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.1.0)
Requirement already satisfied: backcall==0.1.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.1.0)
Requirement already satisfied: click==7.1.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (7.1.1)
Requirement already satisfied: decorator==4.4.2 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (4.4.2)
Requirement already satisfied: docutils==0.16 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.16)
Requirement already satisfied: flask-cors==3.0.8 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (3.0.8)
Requirement already satisfied: flask-socketio==4.2.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (4.2.1)
Requirement already satisfied: flask==1.1.2 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (1.1.2)
Requirement already satisfied: ipython-genutils==0.2.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.2.0)
Requirement already satisfied: ipython==7.13.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (7.13.0)
Requirement already satisfied: itsdangerous==1.1.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (1.1.0)
Requirement already satisfied: janus==0.4.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.4.0)
Requirement already satisfied: jedi==0.16.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.16.0)
Requirement already satisfied: jinja2==2.11.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (2.11.1)
Requirement already satisfied: lockfile==0.12.2 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.12.2)
Requirement already satisfied: markupsafe==1.1.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (1.1.1)
Requirement already satisfied: parso==0.6.2 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.6.2)
Requirement already satisfied: pathtools==0.1.2 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.1.2)
Requirement already satisfied: pexpect==4.8.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (4.8.0)
Requirement already satisfied: pickleshare==0.7.5 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.7.5)
Requirement already satisfied: prompt-toolkit==3.0.5 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (3.0.5)
Requirement already satisfied: ptyprocess==0.6.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.6.0)
Requirement already satisfied: pygments==2.6.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (2.6.1)
Requirement already satisfied: pyjwt==1.7.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (1.7.1)
Requirement already satisfied: python-daemon==2.2.4 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (2.2.4)
Requirement already satisfied: python-engineio==3.12.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (3.12.1)
Requirement already satisfied: python-openflow==2020.1rc1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (2020.1rc1)
Requirement already satisfied: python-socketio==4.5.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (4.5.1)
Requirement already satisfied: six==1.14.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (1.14.0)
Requirement already satisfied: traitlets==4.3.3 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (4.3.3)
Requirement already satisfied: watchdog==0.10.2 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.10.2)
Requirement already satisfied: wcwidth==0.1.9 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.1.9)
Requirement already satisfied: werkzeug==1.0.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (1.0.1)
Requirement already satisfied: setuptools>=18.5 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from ipython==7.13.0->kytos==2020.1rc1) (49.2.1)
Building wheels for collected packages: kytos
  Building wheel for kytos (setup.py) ... done
  Created wheel for kytos: filename=kytos-2020.1rc1-py3-none-any.whl size=1465812 sha256=242a4436242c7dcc8a20e18fdd12bf00329eaab4b9602c08f1db26e8de022ffd
  Stored in directory: /tmp/pip-ephem-wheel-cache-o880myrk/wheels/7f/59/b2/df91a107ec5b96a02a78fdba23f45cb946eeac39aa67cce5b0
Successfully built kytos
Installing collected packages: kytos
Successfully installed kytos-2020.1rc1

2. If wheel isn't installed:

> Collecting pip
  Using cached https://files.pythonhosted.org/packages/bd/b1/56a834acdbe23b486dea16aaf4c27ed28eb292695b90d01dff96c96597de/pip-20.2.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.2.1
Processing /home/gleyberson/Dev/kytos-workspace/dev/core/kytos
Requirement already satisfied: appnope==0.1.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.1.0)
Requirement already satisfied: backcall==0.1.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.1.0)
Requirement already satisfied: click==7.1.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (7.1.1)
Requirement already satisfied: decorator==4.4.2 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (4.4.2)
Requirement already satisfied: docutils==0.16 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.16)
Requirement already satisfied: flask-cors==3.0.8 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (3.0.8)
Requirement already satisfied: flask-socketio==4.2.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (4.2.1)
Requirement already satisfied: flask==1.1.2 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (1.1.2)
Requirement already satisfied: ipython-genutils==0.2.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.2.0)
Requirement already satisfied: ipython==7.13.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (7.13.0)
Requirement already satisfied: itsdangerous==1.1.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (1.1.0)
Requirement already satisfied: janus==0.4.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.4.0)
Requirement already satisfied: jedi==0.16.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.16.0)
Requirement already satisfied: jinja2==2.11.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (2.11.1)
Requirement already satisfied: lockfile==0.12.2 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.12.2)
Requirement already satisfied: markupsafe==1.1.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (1.1.1)
Requirement already satisfied: parso==0.6.2 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.6.2)
Requirement already satisfied: pathtools==0.1.2 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.1.2)
Requirement already satisfied: pexpect==4.8.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (4.8.0)
Requirement already satisfied: pickleshare==0.7.5 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.7.5)
Requirement already satisfied: prompt-toolkit==3.0.5 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (3.0.5)
Requirement already satisfied: ptyprocess==0.6.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.6.0)
Requirement already satisfied: pygments==2.6.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (2.6.1)
Requirement already satisfied: pyjwt==1.7.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (1.7.1)
Requirement already satisfied: python-daemon==2.2.4 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (2.2.4)
Requirement already satisfied: python-engineio==3.12.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (3.12.1)
Requirement already satisfied: python-openflow==2020.1rc1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (2020.1rc1)
Requirement already satisfied: python-socketio==4.5.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (4.5.1)
Requirement already satisfied: six==1.14.0 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (1.14.0)
Requirement already satisfied: traitlets==4.3.3 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (4.3.3)
Requirement already satisfied: watchdog==0.10.2 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.10.2)
Requirement already satisfied: wcwidth==0.1.9 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (0.1.9)
Requirement already satisfied: werkzeug==1.0.1 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from kytos==2020.1rc1) (1.0.1)
Requirement already satisfied: setuptools>=18.5 in /home/gleyberson/Dev/kytos-workspace/envs/iss_kytos1036/lib/python3.7/site-packages (from ipython==7.13.0->kytos==2020.1rc1) (41.2.0)
Using legacy 'setup.py install' for kytos, since package 'wheel' is not installed.
Installing collected packages: kytos
    Running setup.py install for kytos ... done
Successfully installed kytos-2020.1rc1
