### ISSUE TITLE
Verify install procedure and improve the README

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#138]
On an ideal world we should do `pip3 install kyco` and all dependencies should be installed.

This should be tested on debian based distros and CentOS/RedHat.

**Comment by macartur** [comment]
@beraldoleal , the file etc/logging.ini don't was listed in MANIFEST.in, I did  a fix.

**Comment by macartur** [comment]
@beraldoleal, could you update the kyco in pypi, I will test the kyco package in debian, ubuntu, centos and fedora using pip3.

**Comment by beraldoleal** [comment]
I will do this, soon @macartur .

**Comment by beraldoleal** [comment]
We should also check if python3 setup.py install is working as well.

**Comment by macartur** [comment]
OK, I will do this check.

**Comment by macartur** [comment]
@beraldoleal , @raphaelmcobe , @cemsbr , @diraol 

Tests using docker:
| Distribution |  Version              |  install using pip3    | install using python setup.py install    |
| ubuntu        |  xenial  (16.04)   |        don't work      |     working                                            |
| ubuntu        |  trusty  (14.04)     |         working        |     working                                           |
| fedora         |        25                |        working           |      working                                          |
| centos         |        7                  |        working           |            working                                    |
| debian        |       jessie             |          working         |           working                                     |
| debian        |      unstable         |      don't work         |       working                                         |

Don't work because:
  The files ['etc/kyco.conf','etc/logging.ini']   are installed in the same folder of kyco package. Example of installed path: ['/usr/local/lib/python3.4/dist-packages/etc/kyco.conf', '/usr/local/lib/python3.4/dist-packages/etc/logging.ini']
  When kyco binary is running he tries search the files in : ['/etc/kyco.conf', '/etc/logging.ini']
