### ISSUE TITLE
kyco.conf is ignored

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#216]
In _config.py_, kyco.conf file is ignored if there is no _conf_ argument fro.m command line. Much probably this is the cause of #201.

**Comment by macartur** [comment]
I guess this is working now, when you use kytos -f -c <conf_file.conf>, the file is read and the arguments is used.

I changed the port to 8380  and the netstat command displays this:
`tcp        0      0 0.0.0.0:8380            0.0.0.0:*               LISTEN      14259/python3.6`

**Comment by beraldoleal** [comment]
@cemsbr can you confirm, please ?

**Comment by cemsbr** [comment]
Still relevant. The problem still happens when no configuration file is specified and ~/.kytosrc is ignored. Should we read a default configuration file when none is specified (both for root and non-root), @beraldoleal ?

**Comment by beraldoleal** [comment]
@cemsbr @macartur, should be like this:

In order to avoid adding all default values hardcoded (imagine that the list of options can be huge), I think that we should only have one default option: `-c, --config` point to `/etc/kytos/kytos.conf` (this is the default daemon config file). So:

```
1. -c, --config option is present ? If yes, parse and read config file args;
2. if not, parse and read values from default config file (/etc/kytos/kytos.conf);
3. If config file is not present, abort saying that there is no config file.
```

Makes sense ?

**Comment by beraldoleal** [comment]
Maybe this is related to #212.

**Comment by cemsbr** [comment]
@beraldoleal, we have to hardcode default values at least (and, at best, most) once anyway. I think that #212 suggests no default file for `-c --conf` at all. If, instead, we use */etc/kytos/kytos.conf*, should we worry about non-root installs? Maybe using */etc* or *$VIRTUAL_ENV/etc* as we've been using would easily deal with both cases.

**Comment by beraldoleal** [comment]
@cemsbr #212 is not about no default config file. Is a different thing, there.

I know that we have default values now, but I'm thinking to grow and have a lot more options, and the maintenance of adding those values to default. Instead of this, I think that we should go as I said on https://github.com/kytos/kytos/issues/216#issuecomment-290703226

**Comment by beraldoleal** [comment]
I talked with @diraol few minutes ago. I'm going to change my mind, sorry. Let's have a default values hardcoded as it is today. No changes here.

Regarding VirtualEnv vs Real envs. I suggest to use jinja2 templates on config files with a `{{ prefix }}` variable.

**Comment by diraol** [comment]
@macartur are you going to take this issue?
