### ISSUE TITLE
Get software version automatically on argparse

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#27]
On `config.py`, we should get the version automatically when running the software with -v option.

**Comment by abaruchi** [comment]
@beraldoleal This issue was open on July of 2016. On that time we were using `setup.py`, but now we are using `kytos.conf` file. Does this issue still apply? 
If yes, can you please confirm if what you have in mind is something like this:
http://stackoverflow.com/questions/15405636/pythons-argparse-to-show-programs-version-with-prog-and-version-string-formatt

**Comment by beraldoleal** [comment]
@abaruchi I think so. Because version is not on config file, right ?

**Comment by diraol** [comment]
@beraldoleal are you talking about this?
https://github.com/kytos/kytos/blob/master/kytos/core/config.py#L12
[sorry, I really didin't understood the problem!]

**Comment by beraldoleal** [comment]
@diraol yes. Thanks.
