### ISSUE TITLE
Create a better way to export buffers to napps

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#29]
On app `self.add_to_msg_out_buffer` should be more intuitive.

**Comment by diraol** [comment]
I have been thinking about this issue (not only because of the access of buffer methods, but also because of switches access).

Maybe we can think about creating a "Public Controller" class, as a Singleton, that would held everything that we want to expose from the controller.

The `Borg` Design Pattern may help with this process:
https://github.com/faif/python-patterns/blob/master/borg.py

Here are other design patterns that we may consider:
https://github.com/faif/python-patterns

**Comment by beraldoleal** [comment]
I think that a Singleton is not the best solution, since that the apps are not instantiating many "controllers" or "buffers". We should pass this object as argument, like a pointer.

**Comment by diraol** [comment]
For now, as stated on #62, we will just share the controller among NApps.

Considering this, I'm going to do a refactoring on the current code to use this new behavior before new code is added to our source code base.

**Comment by beraldoleal** [comment]
I think that for now we could close this, because of the great work of @diraol on PR #63. Thanks.
