### ISSUE TITLE
Improve static files distribution

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#405]

**Comment by diraol** [comment]
The verbosity is not related to sass build process. The main issue here is that all sass files are packed together with kytos source code, instead of only the pre-built css file, so, while copying all sass files from the original source directory to the "being packed" package, we have a huge amount of "copy file" lines printed by setup.py.

I'll try to address this issue by removing the sass files from the 'kytos' package (and namespace) and avoiding sending it on the "tar.gz", letting just the css file.

**Comment by beraldoleal** [comment]
@diraol ok
