### ISSUE TITLE
instalation keeps last tagged version on pip even for newer clones

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#445]
When installing kytos from a repository clone, the version registered during installation is the last one tagged (2017.1b2.post2 at the moment), even though one is actually installing a newer version from the repository (a few commits ahead maybe). This makes it difficult to distinguish between a tagged (pre-)release and the development version from the repository master branch in github.

**Comment by diraol** [comment]
This happens because this is the version hardcoded on our source code.
There are some alternatives for this.
1) As soon as launching a version (`2017.1b2.post2`) change the version on the source code to the devel version of the next release (`2017.1.b3.dev0` for example).
2) Update the `master version` daily or weekly with something that contains `master` and the date...
3) Update the `master version` with something like `nightly`.

**Comment by erickvermot** [comment]
I vote (1).

**Comment by diraol** [comment]
We have reached an agreement, at least for now, to use the first alternative. I've already addressed this issue on specific Pull Requests on the projects. (but to use `2017.1rc1.dev0` since `2017.1b3` was already released).
