### ISSUE TITLE
message out event handler should not be responsible for packing the message

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#457]
Currently the controller's ``msg_out_event_handler()`` (core/controller.py ln 368) is responsible for packing the message (line 386).
Following the idea that kytos should be able to work with other protocols, I believe this responsibility should be avoided.

I am opening this issue to document it and allow possible discussions, but this will be solved once https://github.com/kytos/kytos/issues/446 is closed.

**Comment by diraol** [comment]
@erickvermot the only part of the `msg_out_event_handler` that has a dependency on OpenFlow Protocol is the logged message (which reads some information from the message header).

The packing itself can be considered `agnostic` on the sense that it is just converting a python object into a binary data to be transmitted throughout the given connection.

The behavior of all events sent to the `message_out` buffer having a message attribute with a pack method seems pretty reasonable to me, no matter the protocol. This can be a convention, defined by us, so that anyone that would like to implement new protocols must use this "interface".

One major advantage of this pattern is to allow the development of NApps that want to "track" information about the messages being sent to the network using many different protocols* and without any overhead of needing to unpack those messages.

*off course that the NApps developer will need to know how to handle each of the protocols to be listened to.

Anyway, this discussion must be postponed until after our 2017.1 release.

**Comment by erickvermot** [comment]
> @erickvermot the only part of the msg_out_event_handler that has a dependency on OpenFlow Protocol is the logged message (which reads some information from the message header).

And the ``pack`` method being called which is a pyof method, that may raise pyof exceptions, etc... If someone builds an invalid message, why put it in the queue all the same, and wait for the msg_out_handler to try to pack it unsuccessfully much later when one doesn't even know where the message was built anymore...

> The packing itself can be considered agnostic on the sense that it is just converting a python object into a binary data to be transmitted throughout the given connection.

... the conversion cannot be considered agnostic, right?

> The behavior of all events sent to the message_out buffer having a message attribute with a pack method seems pretty reasonable to me, no matter the protocol. This can be a convention, defined by us, so that anyone that would like to implement new protocols must use this "interface".

I don't see why limit the user... If he has a binary message he wants to send (from a history replay for ex), why forbid him?

> One major advantage of this pattern is to allow the development of NApps that want to "track" information about the messages being sent to the network using many different protocols* and without any overhead of needing to unpack those messages.

Well I see it the other way around, if one wants to keep track of the messages being sent, having the packed message could avoid having to pack it multiple times... + if the messages are from many different protocols, then it is much better if they are packed, since the attributes of the supposed python objects would certainly be different from one another...

> *off course that the NApps developer will need to know how to handle each of the protocols to be listened to.

If they need to know how to handle each one, better leave the task to them then...

> Anyway, this discussion must be postponed until after our 2017.1 release.

ok, since you guys told not to implement #446 before that.

**Comment by cemsbr** [comment]
The user should be able to abstract ``pack``, ``unpack`` and bytes (as it is now). For this, we can require the implementation of a "packable" interface and use non-protocol-specific exceptions for the protocol-agnostic controller to catch.

The python-openflow lib (and future libs of other protocols) aims at abstracting low-level byte manipulation and, so far, nobody has requested to write bytes in buffers without using the lib.

Yes, we can do better than having packing errors right before sending the message, but I believe this is part of validation, another issue.
