### ISSUE TITLE
Bug web-ui

### ISSUE THREAD

**Issue by macartur** [kytos/kytos#461]
When Kytos terminal is minimized I can move and hide switches, connections, and hosts easily.

![kytos-terminal_closed](https://user-images.githubusercontent.com/2965806/27335774-0da80936-55a4-11e7-8dd9-ac2952f29ea9.png)

**Comment by macartur** [comment]
Mapbox is on top of all the elements.

**Comment by diraol** [comment]
@macartur you can or you can't move switches and hosts?
Can you please add a more detailed description on this issue? [Edit the issue description instead of just adding comments].

Try adding/answering the following questions:

1) What is the expected behavior?
2) What is the current behavior?
3) What should be causing the undesired behavior?
4) What may fix it?

**Comment by diraol** [comment]
The bug could not be reproduced. I'm closing the issue for now. If it shows up again reopen it.
