### ISSUE TITLE
Unable to run kytos as regular user even after fresh install

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#543]
Since 07Jul, it is no longer possible to run kytos as a regular user.
It is now trying to create napps dir inside ``/var/lib`` during runtime, which is not possible by regular users.
https://github.com/kytos/kytos/commit/a8153507805444b78781ce090fcd14b37167bb55#diff-8bc31c20cd5303df1ce2ccc1de508fc0R32

Before that it was possible to run kytos normally as a regular user.
There was the problem of ``/var/run/kytos`` being deleted after reboot in some systems using recent versions of systemd, but everything worked ok with a fresh install. (see https://github.com/kytos/kytos/issues/381)

workaround is the same as for the other issue
``sudo mkdir -m 777 /var/lib/kytos``

**Comment by viniarck** [comment]
Wouldn't it be better if kytos were to have all of its configuration under XDG Base directory such ~/.config/kytos?

**Comment by cemsbr** [comment]
Using a standard is a good suggestion. For now, we recommend regular users to create their own Python virtual environment.

**Comment by beraldoleal** [comment]
We can use XDG Base directory, but we have to keep in mind that in a near future kytos will be installed and executed as a system user, like "kytos" user. And this user will not have a "/home" dir. So because of that i think that is better to use `/var/lib/kytos` instead.

@cemsbr python venv should be used only for development, for now.
