### ISSUE TITLE
Define a way to configure available VLANS for Interfaces

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos#684]
And implement it as well.

**Comment by viniarck** [comment]
@beraldoleal, @hdiogenes @macartur @llgoncalves 

This is also very important when the release is going to be deployed in production, for example, at AmLight, there are certain VLANs that can't be used by OpenFlow, otherwise this would lead to other issues since some VLANs are reserved for other things out of the OpenFlow domain. It was in the blueprint:

```
*For each Interface object:*
Each Interface object will have its own VLAN pool with pop() and push()
methods. This pool will be used for EPLs. Administrator might predefine via
configuration the VLAN pool to be used (for instance, VLAN 100 to 200).
```

A quick temporary fix would be to pre-define a global range that should be used by all interfaces, instead of the whole range(1, 4095), and to have a global vlan range in kytos.cfg.

**Comment by beraldoleal** [comment]
To follow the blueprint we must have the default range from 1 to 4095. But yes, I agree, we must have a config file to allow "custom" ranges.
