### ISSUE TITLE
[discussion] NApps runtime settings.py reconfiguration?

### ISSUE THREAD

**Issue by viniarck** [kytos/kytos#834]
Should we support runtime settings configuration changes on NApps? Currently, the module settings.py is either read during setup time or in a loop, but there's no notification event-based changes that the user might use on their code. So, this implies that the user will have to restart the NApp for the settings.py module be read again. As a result, this might be an issue for NApps that aren't using storehouse for persisting data structures and other kind of dynamic information that the NApp is responsible for.

Another alternative that occurred to me, if we ever support this, should be all settings.py should be mapped to REST endpoints for runtime configuration, and the persistence should be backed by storehouse.

**Comment by beraldoleal** [comment]
Hi @viniarck , thanks for this topic.

I don't think that we should support all settings on REST. At least for now. On the future, yes. Because we need to think what are the possible parameters (lists, strings, integers, paths, etc..) and make a proper validation on REST endpoints.

About, NApps be able to reload their configuration settings, I think that is valid and we should implement. But each NApp is a different case/approach.

And we should implement this on method "reload", or something. So if some NApp is reladed AND implements a reload configfile it will work fine.

**Comment by hdiogenes** [comment]
@viniarck in fact, settings weren't being reloaded on napp reload, but this is now fixed (since 2019.1b1, issue #847).

**Comment by viniarck** [comment]
@hdiogenes Amazing! I guess this issue should be closed then. It's nice know that Kytos now has this feature.

**Comment by hdiogenes** [comment]
@viniarck It's important for you to know that, currently, `reload` isn't as soft as the name indicates: it will first unload and then load the NApp again, which may not be what you want here.

**Comment by viniarck** [comment]
@hdiogenes right. But since storehouse provides a DB I believe storehouse would cover a bunch of use cases to restore the current state of the NApp of other runtime data that the developer might want to store. Feel free to keep this issue open I guess it's a decision of how the team will tell users to design their applications to handle runtime configuration changes.

**Comment by hdiogenes** [comment]
I've talked to @beraldoleal and he agrees that, with the fix on #847, we can close this for now.
