### ISSUE TITLE
Kytosd running in background does not work

### ISSUE THREAD

**Issue by ajoaoff** [kytos/kytos#893]
When `kytosd` is launched in background it is not opening TCP ports, neither for HTTP nor for the controller.

**Comment by hdiogenes** [comment]
Please, try setting the DEBUG loglevel in kytos logging.ini and attaching the output here.

**Comment by dgarc330** [comment]
Output when running kytosd :

May 28 13:11:51 [localhost] journal: kytos.core.logs:INFO logs:57:  Logging config file "/usr/local/python-kytos/etc/kytos/logging.ini" loaded successfully.
May 28 13:11:51 [localhost] journal: controller:INFO controller:150:  /usr/local/python-kytos/var/run/kytos
May 28 13:11:51 [localhost] journal: controller:INFO controller:198:  Starting Kytos - Kytos Controller
May 28 13:11:51 [localhost] journal: controller:INFO controller:205:  Starting TCP server: <kytos.core.atcp_server.KytosServer object at 0x7fc6b3ee0668>
May 28 13:11:51 [localhost] journal: atcp_server:INFO atcp_server:68:  Kytos listening at 0.0.0.0:6633
May 28 13:11:51 [localhost] journal: controller:INFO controller:238:  ThreadPool started: <concurrent.futures.thread.ThreadPoolExecutor object at 0x7fc6b25e16a0>
May 28 13:11:51 [localhost] journal: controller:INFO controller:244:  Loading Kytos NApps...
May 28 13:11:51 [localhost] journal: kytos.core.napps.napp_dir_listener:INFO napp_dir_listener:40:  NAppDirListener Started...

**Comment by dgarc330** [comment]
Output when running kytosd -D:

May 28 13:13:09 [localhost] journal: kytos.core.logs:INFO logs:57:  Logging config file "/usr/local/python-kytos/etc/kytos/logging.ini" loaded successfully.
May 28 13:13:09 [localhost] journal: controller:INFO controller:150:  /usr/local/python-kytos/var/run/kytos
May 28 13:13:09 [localhost] journal: controller:INFO controller:198:  Starting Kytos - Kytos Controller
May 28 13:13:09 [localhost] journal: controller:INFO controller:205:  Starting TCP server: <kytos.core.atcp_server.KytosServer object at 0x7f0d5ecd36a0>
May 28 13:13:09 [localhost] journal: atcp_server:INFO atcp_server:68:  Kytos listening at 0.0.0.0:6633
May 28 13:13:09 [localhost] journal: controller:INFO controller:238:  ThreadPool started: <concurrent.futures.thread.ThreadPoolExecutor object at 0x7f0d5d3d4710>
May 28 13:13:09 [localhost] journal: controller:INFO controller:244:  Loading Kytos NApps...
May 28 13:13:09 [localhost] journal: kytos.core.napps.napp_dir_listener:INFO napp_dir_listener:40:  NAppDirListener Started...

**Comment by hdiogenes** [comment]
Thank you @dgarc330! I'm also attaching the output of `strace -f kytosd` so that we can know better where it is failing. It seems to loop forever on this call to `close()`.

<details>
<summary>strace output</summary>
<pre>
...
read(8, "!\322\320By\344U_\3\342\257\n\316?\\J\230\233\36\6$\250\313i\16b70&\2405\235"..., 130) = 130
stat("/home/humberto/kytos/kytos/core/../web-ui", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
close(8)                                = 0
mkdir("/home/humberto/envs/kytos/var/lib/kytos/napps", 0755) = -1 EEXIST (File exists)
stat("/home/humberto/envs/kytos/var/lib/kytos/napps", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
getpid()                                = 688
fstat(7, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
rt_sigaction(SIGINT, {sa_handler=0x7f5bf9f92930, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f5bfa2f43c0}, {sa_handler=0x7f5bf9f92930, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f5bfa2f43c0}, 8) = 0
rt_sigaction(SIGINT, NULL, {sa_handler=0x7f5bf9f92930, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f5bfa2f43c0}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x7f5bf9f92930, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f5bfa155e00}, NULL, 8) = 0
fstat(7, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
rt_sigaction(SIGTERM, {sa_handler=0x7f5bf9f92930, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f5bfa2f43c0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTERM, NULL, {sa_handler=0x7f5bf9f92930, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f5bfa2f43c0}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0x7f5bf9f92930, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f5bfa155e00}, NULL, 8) = 0
getuid()                                = 1000
getgid()                                = 1000
getppid()                               = 685
fcntl(0, F_DUPFD_CLOEXEC, 0)            = 8
getsockopt(8, SOL_SOCKET, SO_TYPE, 0x7fff56243420, [4]) = -1 ENOTSOCK (Socket operation on non-socket)
getsockname(8, 0x7fff56242f70, [16])    = -1 ENOTSOCK (Socket operation on non-socket)
getpeername(8, 0x7fff56242f70, [16])    = -1 ENOTSOCK (Socket operation on non-socket)
close(8)                                = 0
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5bf726f000
prlimit64(0, RLIMIT_CORE, NULL, {rlim_cur=RLIM64_INFINITY, rlim_max=RLIM64_INFINITY}) = 0
prlimit64(0, RLIMIT_CORE, {rlim_cur=0, rlim_max=0}, NULL) = 0
umask(000)                              = 022
chdir("/")                              = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 8
connect(8, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(8)                                = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 8
connect(8, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(8)                                = 0
openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = 8
lseek(8, 0, SEEK_CUR)                   = 0
fstat(8, {st_mode=S_IFREG|0644, st_size=818, ...}) = 0
read(8, "root:x:0:0::/root:/bin/bash\nbin:"..., 4096) = 818
close(8)                                = 0
setgid(1000)                            = 0
setuid(1000)                            = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5bf9c178d0) = 692
exit_group(0)                           = ?
+++ exited with 0 +++
strace: Process 692 attached
set_robust_list(0x7f5bf9c178e0, 24)     = 0
getpid()                                = 692
getrandom("\x99\x35\x70\x09\x79\x26\x58\x69\x0a\x3f\x0b\xcf\xf7\xc7\xa1\x3a\x02\x5e\xf0\xf4\xe0\x16\x27\x97\x69\x58\x39\xdb\xcb\xad\x77\xa3"..., 2496, GRND_NONBLOCK) = 2496
setsid()                                = 692
clone(strace: Process 693 attached
 <unfinished ...>
[pid   693] set_robust_list(0x7f5bf9c178e0, 24) = 0
[pid   693] getpid()                    = 693
[pid   693] getrandom("\x27\xda\x7b\x80\xa6\x7c\x50\xcf\xbf\xc9\x31\xcc\x6a\x51\xab\xad\x90\x95\x12\x68\x29\x95\xd5\x56\x85\xe0\x65\x67\x34\xdd\xc4\xc8"..., 2496, GRND_NONBLOCK) = 2496
[pid   692] <... clone resumed> child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5bf9c178d0) = 693
[pid   692] exit_group(0)               = ?
[pid   692] +++ exited with 0 +++
rt_sigaction(SIGTSTP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f5bfa2f43c0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTTIN, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f5bfa2f43c0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTTOU, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f5bfa2f43c0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0x7f5bf9f92930, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f5bfa2f43c0}, {sa_handler=0x7f5bf9f92930, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f5bfa155e00}, 8) = 0
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=512*1024}) = 0
close(524287)                           = -1 EBADF (Bad file descriptor)
close(524286)                           = -1 EBADF (Bad file descriptor)
close(524285)                           = -1 EBADF (Bad file descriptor)
close(524284)                           = -1 EBADF (Bad file descriptor)
close(524283)                           = -1 EBADF (Bad file descriptor)
close(524282)                           = -1 EBADF (Bad file descriptor)
close(524281)                           = -1 EBADF (Bad file descriptor)
close(524280)                           = -1 EBADF (Bad file descriptor)
...
</pre>
</details>

**Comment by ajoaoff** [comment]
I saw this in the log when running in background:

```
May 29 11:05:59 develop asyncio:DEBUG selector_events:148:  Fail to write a null byte into the self-pipe socket#012Traceback (most recent call last):#012  File "/usr/lib/python3.7/asyncio/selector_events.py", line 143, in _write_to_self#012    csock.send(b'\0')#012
OSError: [Errno 9] Bad file descriptor
```

I don't see that line when running in foreground.
It looks like to be related to what you saw with `strace`.
