### ISSUE TITLE
Create PyPI project description to kytos, kytos-utils and python-openflow.

### ISSUE THREAD

**Issue by gleybersonandrade** [kytos/kytos#898]
Today, kytos projects don't have a description in PyPI.

**Comment by hdiogenes** [comment]
From PyPI settings:

"To set the 'kytos' description, author, links, classifiers, and other details for your next release, use the setup() arguments in your setup.py file [1]. Updating these fields will not change the metadata for past releases. Additionally, you must use Twine to upload your files in order to get full support for these fields. See the Python Packaging User Guide for more help."

[1] https://packaging.python.org/tutorials/packaging-projects/#setup-args
