### ISSUE TITLE
Install error without virtualenv

### ISSUE THREAD

**Issue by jibanli** [kytos/kytos#968]
![111](https://user-images.githubusercontent.com/39478794/67159767-daddb280-f37b-11e9-818f-e453fccb70dd.png)

**Comment by rmotitsuki** [comment]
Hi jibanli,
Thank you for using Kytos.
The error happens because the Python command has "sudo".
When you run the command with "sudo" you will use the Python from your OS.
I see that you are using the virtual env (py36). I think that if you run the command "python setup.py install" without the "sudo" you will be OK.

You can check the Python versions you have running the commands:

```
	sudo python --version
	sudo which python
	
	python --version
	which python
```

**Comment by jibanli** [comment]
![无标题3](https://user-images.githubusercontent.com/39478794/67254042-76227500-f4ad-11e9-81a9-16130195a8fb.png)

**Comment by jibanli** [comment]
Thank you. But a new error happened....

**Comment by rmotitsuki** [comment]
It seems a error installing Kytos outside the virtual env. I´ll fix it and open a PR to the project.

**Comment by hdiogenes** [comment]
@jibanli it looks like this issue has been fixed by @rmotitsuki's last PR. Can you try again and report back to us?

**Comment by jibanli** [comment]
![kytos_env](https://user-images.githubusercontent.com/39478794/70386880-2d7d3780-19d9-11ea-9693-c2ea19be7427.png)

**Comment by jibanli** [comment]
I succeeded installing kytos using anaconda3 by creating py3.6 environment.

**Comment by hdiogenes** [comment]
Nice, @jibanli. Thank you!
